---
network_ethernet_interfaces:
  - device: eth0
    bootproto: static
    address: "{{ admin_ip }}"
    netmask: 255.255.255.0
    gateway: "{{ admin_ip_gateway }}"
  - device: eth1
    bootproto: static
    address: "{{ mgmt_ip }}"
  - device: eth2
    bootproto: static
  - device: eth2.2504
    bootproto: static
    address: "{{ public_ip }}"
    vlan: yes
  - device: eth3
    bootproto: static
    address: "{{ sp_ip }}"
