---

openstack_host_upgrade: False

## database
openstack_db_host: "{{ openstack_controller_host }}"
openstack_db_root_user: "{{ mysql_users[0].name }}"
openstack_db_root_password: "{{ mysql_users[0].password }}"

## network
openstack_admin_vip: "{{ openstack_controller_host }}"

openstack_internal_vip: "{{ openstack_controller_host }}"
openstack_internal_net: "10.0.1.0"
openstack_internal_netmask: "24"
openstack_internal_interface: eth1

openstack_public_vip: "172.23.62.10"
openstack_public_netmask: "24"
openstack_public_interface: eth2
openstack_public_vlan: 2562


## memcached

memcached_port: 11211
openstack_memcached_servers: "{% for host in groups['memcached'] %}{{ hostvars[host]['mgmt_ip'] }}:{{ memcached_port }}{% if not loop.last %},{% endif %}{% endfor %}"

## RabbitMQ
openstack_rabbit_host: "{{ openstack_controller_host }}"
#openstack_rabbit_hosts: "{% for host in groups['rabbitmq'] %}{{ hostvars[host]['mgmt_ip'] }}:5672{% if not loop.last %},{% endif %}{% endfor %}"

## keystone auth
openstack_keystone_auth_uri: "http://{{ openstack_controller_host }}:5000"
openstack_keystone_auth_url: "http://{{ openstack_controller_host }}:35357"
openstack_keystone_admin_token: "openstack"
openstack_admin_user: "admin"
openstack_admin_password: "openstack"

## other
openstack_controller_host: "10.0.1.10"

# openstack-common
#openstack_repos:
#  - name: centos-openstack-mitaka
#    baseurl: http://mirrors.aliyun.com/centos/7/cloud/$basearch/openstack-mitaka/
#    gpgcheck: no



## nova
openstack_libvirt_secret_uuid: "{{ 10000 | random | to_uuid }}"

## auth env
token_auth_env:
  OS_TOKEN: "{{ openstack_keystone_admin_token }}"
  OS_URL: "http://{{ openstack_controller_host }}:35357/v3"
  OS_IDENTITY_API_VERSION: "3"

## nova
nova_keystone_user: "nova"
nova_keystone_password: "nova"
