---
# network
network_bond_interfaces:
  - device: bond0
    bootproto: static
    vlan: yes
    address: "{{ admin_ip }}"
    netmask: 255.255.255.0
    gateway: "{{ admin_ip_gateway }}"
    bond_mode: 1
    bond_slaves: [eth0]
  - device: bond1
    bootproto: static
    address: "{{ sp_ip }}"
    bond_mode: 1
    bond_slaves: [eth1]
#  - device: bond2
#    bootproto: static
#    address: "{{ sc_ip }}"
#    bond_mode: 1
#    bond_slaves: [eth2]

# ceph-common
ceph_repo_enable: True

#ceph_cluster_network: "10.0.3.0/24"
#cep_mon_host: "{{ hostvars[groups['ceph-mon'][0]]['sp_ip'] }}, {{ hostvars[groups['ceph-mon'][1]]['sp_ip'] }}, {{ hostvars[groups['ceph-mon'][2]]['sp_ip'] }}"

# openstack
ceph_openstack_config: True

# Monitor options

monitor_secret: AQAnV5dWAAAAABAA/gEcrn76zFfFBp8NTdxfNQ==

# cephx options
cephx: True

# Devices to be used as OSDs
devices:
  - /dev/vdb

# Use 'None' to undefined the variable.
# Using 'None' will colocate both journal and data on the same disk
# creating a partition at the beginning of the device
#
#journal_device: "/dev/sdb"
