---
network_bond_interfaces:
  - device: bond0
    bootproto: static
    vlan: yes
    address: "{{ admin_ip }}"
    netmask: 255.255.255.0
    gateway: "{{ admin_ip_gateway }}"
    bond_mode: 1
    bond_slaves: [eth0]
  - device: bond1
    bootproto: static
    vlan: yes
    address: "{{ mgmt_ip }}"
    bond_mode: 1
    bond_slaves: [eth1]
  - device: bond2
    bootproto: static
    vlan: yes
    bond_mode: 1
    bond_slaves: [eth2]
  - device: bond2.2504
    bootproto: static
    vlan: yes
    address: "{{ public_ip }}"
    netmask: 255.255.255.0
    bond_mode: 1
    bond_slaves: []
  - device: bond3
    bootproto: static
    address: "{{ sp_ip }}"
    bond_mode: 1
    bond_slaves: [eth3]
