---
# Galera MariaDB
mariadb_repo: False
galera_wsrep_cluster_address: ["{{ hostvars[groups['galera'][0]]['mgmt_ip'] }}", "{{ hostvars[groups['galera'][1]]['mgmt_ip'] }}", "{{ hostvars[groups['galera'][2]]['mgmt_ip'] }}"]
galera_bootstrap_node: "{{ hostvars[groups['galera'][0]].inventory_hostname }}"
mariadb_root_username: root
mariadb_root_password: root
mariadb_users:
  - { name: "root", host: "%", password: "root", priv: "*.*:GRANT,ALL" }
galera_clustercheck_enable: true
galera_clustercheck_username: clustercheck
galera_clustercheck_password: clustercheck
