---

## database
openstack_db_host: "{{ openstack_controller_host }}"
openstack_db_root_user: "{{ mariadb_users[0].name }}"
openstack_db_root_password: "{{ mariadb_users[0].password }}"

## network
openstack_admin_vip: "{{ openstack_controller_host }}"
openstack_internal_vip: "{{ openstack_controller_host }}"
openstack_public_vip: "172.23.40.11"

## memcached
memcached_port: 11211
openstack_memcached_servers: "{% for host in groups['memcached'] %}{{ hostvars[host]['mgmt_ip'] }}:{{ memcached_port }}{% if not loop.last %},{% endif %}{% endfor %}"

## RabbitMQ
#openstack_rabbit_host: "{{ openstack_controller_host }}"
openstack_rabbit_hosts: "{% for host in groups['rabbitmq'] %}{{ hostvars[host]['mgmt_ip'] }}:5672{% if not loop.last %},{% endif %}{% endfor %}"

## keystone auth
openstack_keystone_auth_uri: "http://{{ openstack_controller_host }}:5000"
openstack_keystone_auth_url: "http://{{ openstack_controller_host }}:35357"
openstack_keystone_admin_token: "openstack"
openstack_admin_user: "admin"
openstack_admin_password: "openstack"

## other
openstack_controller_host: "10.0.1.10"

# corosync
openstack_corosync_bindnetaddr: "{{ openstack_internal_net }}"
openstack_corosync_mcastaddr: "239.255.42.1"
openstack_corosync_mcastport: 5405
openstack_hacluster_password: "openstack"

# openstack-common
openstack_repos:
  - name: centos-openstack-liberty
    description: CentOS-7 - OpenStack liberty
    baseurl: http://mirrors.aliyun.com/centos/7/cloud/x86_64/openstack-liberty/
    gpgcheck: no

## ceph

ceph_repo_baseurl: "http://mirrors.aliyun.com/ceph/rpm-firefly/el7/"
ceph_fsid: "cc546e6b-52ab-456b-8283-adff1cd61bce"
openstack_keys:
  - { name: glance, owner: "glance" }
  - { name: cinder, owner: "cinder" }
  - { name: cinder-backup, owner: "cinder" }

openstack_libvirt_secret_uuid: "c27421a6-c4ce-4236-b96c-e4ac19c53a7d"

# openstack controller && compute
openstack_internal_net: "10.0.1.0"
openstack_internal_netmask: "24"
openstack_public_netmask: "24"

## auth env
token_auth_env:
  OS_TOKEN: "{{ openstack_keystone_admin_token }}"
  OS_URL: "http://{{ openstack_controller_host }}:35357/v3"
  OS_IDENTITY_API_VERSION: "3"

## nova
nova_keystone_user: "nova"
nova_keystone_password: "nova"

## neutron
neutron_public_interface: "bond2"
