---

## ceph-common
- name: Ceph Node Base Configure.
  hosts: ceph
  remote_user: root
  roles:
    - role: ansible-role-ceph-common

## ceph-mon
- name: Ceph Mon Node Configure.
  hosts: ceph-mon
  remote_user: root
  roles:
    - role: ansible-role-ceph-mon

## ceph-osd
- name: Ceph OSD Node Configure.
  hosts: ceph-osd
  serial: 1
  remote_user: root
  roles:
    - role: ansible-role-ceph-osd
