---

# Ansible Controller node
- name: Generate ssh key for nova user.
  hosts: localhost
  connection: local
  tasks:
    - name: Generate ssh key for nova user.
      shell: |
        mkdir -p "{{ inventory_dir }}/fetch/compute"
        rm -rf "{{ inventory_dir }}/fetch/compute/id_rsa*"
        ssh-keygen -N '' -q -f "{{ inventory_dir }}/fetch/compute/id_rsa"
      args:
        creates: "{{ inventory_dir }}/fetch/compute/id_rsa"

- name: Installation and setup of nova compute.
  hosts: nova_compute
  remote_user: root
  roles:
    - role: "ansible-role-ceph-client"
    - role: "ansible-role-openstack-nova"
