---

# Init openstack host
- include: setup-hosts.yml

# MySQL Database
- name: Install MySQL Database.
  hosts: galera
  remote_user: root
  roles:
    - role: ansible-role-mysql

# RabbitMQ
- include: rabbitmq-install.yml

# Memcached
- include: memcached-install.yml

# HAproxy
- include: haproxy-install.yml

# VIP
- name: Install and Configure VIP.
  hosts: haproxy
  remote_user: root
  pre_tasks:
    - name: Configure ip
      shell: |
        ip addr add {{ openstack_internal_vip }}/{{ openstack_internal_netmask }} dev {{ openstack_internal_interface }}
        ip addr add {{ openstack_public_vip }}/{{ openstack_public_netmask }} dev {{ openstack_public_interface }}.{{ openstack_public_vlan }}
      ignore_errors: True

# setup openstack
- include: setup-openstack.yml
